export const dataBlog = [
    {title: 'Some quick example text to build on the card title and make up the bulk'},
    {title: 'Some quick example text to build on the card title and make up the bulk'},
    {title: 'Some quick example text to build on the card title and make up the bulk'},
    {title: 'Some quick example text to build on the card title and make up the bulk'},
    {title: 'Some quick example text to build on the card title and make up the bulk'},
    {title: 'Some quick example text to build on the card title and make up the bulk'},
    {title: 'Some quick example text to build on the card title and make up the bulk'},
    {title: 'Some quick example text to build on the card title and make up the bulk'},
    {title: 'Some quick example text to build on the card title and make up the bulk'},
    {title: 'Some quick example text to build on the card title and make up the bulk'},
    {title: 'Some quick example text to build on the card title and make up the bulk'},
    {title: 'Some quick example text to build on the card title and make up the bulk'},
    {title: 'Some quick example text to build on the card title and make up the bulk'},
    {title: 'Some quick example text to build on the card title and make up the bulk'},
    {title: 'Some quick example text to build on the card title and make up the bulk'},
    {title: 'Some quick example text to build on the card title and make up the bulk'},
    {title: 'Some quick example text to build on the card title and make up the bulk'},
    {title: 'Some quick example text to build on the card title and make up the bulk'},
    {title: 'Some quick example text to build on the card title and make up the bulk'},
    {title: 'Some quick example text to build on the card title and make up the bulk'},
];